name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Read Flutter version
        id: flutter_version
        run: echo "version=$(cat flutter-version.txt)" >> $GITHUB_OUTPUT

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ steps.flutter_version.outputs.version }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter unit tests
        run: flutter test --reporter=failures-only

      - name: Analyze package
        run: dart analyze --fatal-infos lib test

      - name: Example pub get
        run: flutter pub get
        working-directory: example

      - name: Analyze example
        run: dart analyze --fatal-infos example/lib
